# Generated by Django 4.0.3 on 2022-04-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_query_query2_delete_order_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QUERY2',
            new_name='Query_2',
        ),
    ]
