# Generated by Django 4.0.3 on 2022-04-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_rename_query2_query_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=200, null=True)),
                ('software_id', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('INBOUND', 'INBOUND'), ('OUTBOUND', 'OUTBOUND'), ('RETAIL', 'RETAIL'), ('NEW', 'NEW')], max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Query_2',
        ),
        migrations.RemoveField(
            model_name='query',
            name='category',
        ),
        migrations.RemoveField(
            model_name='query',
            name='description',
        ),
        migrations.RemoveField(
            model_name='query',
            name='name',
        ),
        migrations.RemoveField(
            model_name='query',
            name='software_id',
        ),
        migrations.AddField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('UNDER_PROGRESS', 'UNDER_PROGRESS'), ('TEAM_REVIEWING', 'TEAM_REVIEWING'), ('RESOLVED', 'RESOLVED')], max_length=100, null=True),
        ),
    ]
