# Generated by Django 4.0.3 on 2022-04-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_detail_delete_query_2_remove_query_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='Query1',
        ),
    ]
