# Generated by Django 4.0.2 on 2022-04-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_remark_detail_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='tags',
            field=models.ManyToManyField(to='CRM.Remark'),
        ),
    ]
